# Generated by Django 5.2.15 on 2026-06-03 17:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_rename_care_access_staff_p_975b96_idx_care_access_staff_p_5a043e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_type', models.CharField(choices=[('PRIMARY_CARE', 'Primary care'), ('FOLLOW_UP', 'Follow up'), ('PATRONAGE', 'Patronage'), ('PERINATAL', 'Perinatal'), ('LAB', 'Lab'), ('IMAGING', 'Imaging'), ('SPECIALIST', 'Specialist'), ('EMERGENCY', 'Emergency')], db_index=True, default='PRIMARY_CARE', max_length=32)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Checked in'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], db_index=True, default='SCHEDULED', max_length=20)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('SOON', 'Soon'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], db_index=True, default='ROUTINE', max_length=20)),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('reason', models.CharField(max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('assigned_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('department_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='care.department')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='care.hospital')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='care.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='care.patient')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='care.room')),
            ],
            options={
                'ordering': ['scheduled_start', 'patient__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter_type', models.CharField(choices=[('OUTPATIENT', 'Outpatient'), ('INPATIENT', 'Inpatient'), ('EMERGENCY', 'Emergency'), ('HOME_VISIT', 'Home visit'), ('TELEHEALTH', 'Telehealth'), ('PERINATAL', 'Perinatal')], default='OUTPATIENT', max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SIGNED', 'Signed'), ('AMENDED', 'Amended'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter', to='care.appointment')),
                ('department_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='care.department')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='care.hospital')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='care.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='care.patient')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='care.room')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergen', models.CharField(max_length=180)),
                ('reaction', models.CharField(blank=True, max_length=240)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('LIFE_THREATENING', 'Life threatening')], db_index=True, default='MODERATE', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ENTERED_IN_ERROR', 'Entered in error')], db_index=True, default='ACTIVE', max_length=32)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_allergies', to='care.hospital')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_allergies', to='care.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='care.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_allergies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['allergen'],
            },
        ),
        migrations.CreateModel(
            name='PatientVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('glucose_mmol_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals', to='care.encounter')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_vitals', to='care.hospital')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_vitals', to='care.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='care.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'scheduled_start'], name='care_appoin_organiz_4767d7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital', 'scheduled_start'], name='care_appoin_hospita_159d39_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['assigned_provider', 'scheduled_start'], name='care_appoin_assigne_b8c413_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'scheduled_start'], name='care_appoin_status_5e1a85_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'scheduled_start'], name='care_appoin_patient_9b5136_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['organization', 'started_at'], name='care_encoun_organiz_ba2c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['hospital', 'started_at'], name='care_encoun_hospita_749d76_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', 'started_at'], name='care_encoun_patient_190645_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['provider', 'started_at'], name='care_encoun_provide_8207b0_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status', 'started_at'], name='care_encoun_status_da6298_idx'),
        ),
        migrations.AddIndex(
            model_name='patientallergy',
            index=models.Index(fields=['organization', 'status'], name='care_patien_organiz_ff3041_idx'),
        ),
        migrations.AddIndex(
            model_name='patientallergy',
            index=models.Index(fields=['patient', 'status'], name='care_patien_patient_cf301c_idx'),
        ),
        migrations.AddIndex(
            model_name='patientallergy',
            index=models.Index(fields=['severity', 'status'], name='care_patien_severit_74d05f_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvital',
            index=models.Index(fields=['organization', 'measured_at'], name='care_patien_organiz_031093_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvital',
            index=models.Index(fields=['patient', 'measured_at'], name='care_patien_patient_cf6d29_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvital',
            index=models.Index(fields=['encounter', 'measured_at'], name='care_patien_encount_16690d_idx'),
        ),
    ]
