# Generated by Django 5.2.15 on 2026-06-03 20:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_phase_2b_care_coordination_orders_admissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('NEEDS_REVIEW', 'Needs review'), ('CONFIRMED', 'Confirmed duplicate'), ('DISMISSED', 'Dismissed'), ('MERGED', 'Merged')], db_index=True, default='NEEDS_REVIEW', max_length=20)),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('duplicate_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidate_matches', to='care.patient')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_duplicate_candidates', to='care.hospital')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_duplicate_candidates', to='care.organization')),
                ('primary_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_duplicate_candidates', to='care.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_duplicate_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-score', '-detected_at'],
                'indexes': [models.Index(fields=['organization', 'status', 'score'], name='care_patien_organiz_c01d59_idx'), models.Index(fields=['hospital', 'status'], name='care_patien_hospita_045f65_idx'), models.Index(fields=['primary_patient', 'status'], name='care_patien_primary_3ab724_idx'), models.Index(fields=['duplicate_patient', 'status'], name='care_patien_duplica_e47be2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('primary_patient', models.F('duplicate_patient')), _negated=True), name='duplicate_candidate_patients_must_differ'), models.UniqueConstraint(fields=('organization', 'primary_patient', 'duplicate_patient'), name='unique_duplicate_candidate_pair_per_org')],
            },
        ),
        migrations.CreateModel(
            name='PatronageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_type', models.CharField(choices=[('ROUTINE', 'Routine'), ('HIGH_RISK', 'High risk'), ('POST_DISCHARGE', 'Post discharge'), ('PERINATAL', 'Perinatal'), ('CHRONIC', 'Chronic'), ('NEWBORN', 'Newborn')], db_index=True, default='ROUTINE', max_length=32)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('OFFLINE_QUEUED', 'Offline queued'), ('SYNCED', 'Synced'), ('CONFLICT', 'Conflict'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=32)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('ROUTINE', 'Routine'), ('SOON', 'Soon'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], db_index=True, default='ROUTINE', max_length=20)),
                ('territory', models.CharField(blank=True, db_index=True, max_length=120)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('visited_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('client_reference', models.CharField(blank=True, db_index=True, max_length=160)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=160)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('server_version', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('conflict_payload', models.JSONField(blank=True, default=dict)),
                ('conflict_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patronage_visits', to='care.staffprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patronage_visits', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patronage_visits', to='care.hospital')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patronage_visits', to='care.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patronage_visits', to='care.patient')),
            ],
            options={
                'ordering': ['status', 'scheduled_for'],
                'indexes': [models.Index(fields=['organization', 'status', 'scheduled_for'], name='care_patron_organiz_6b0ba0_idx'), models.Index(fields=['hospital', 'status', 'scheduled_for'], name='care_patron_hospita_c67c60_idx'), models.Index(fields=['patient', 'scheduled_for'], name='care_patron_patient_43d5b1_idx'), models.Index(fields=['assigned_to', 'status', 'scheduled_for'], name='care_patron_assigne_b7b579_idx'), models.Index(fields=['territory', 'status'], name='care_patron_territo_cfb9f2_idx'), models.Index(fields=['idempotency_key', 'status'], name='care_patron_idempot_a47c1c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerinatalRegistryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WATCHLIST', 'Watchlist'), ('HOSPITALIZED', 'Hospitalized'), ('DELIVERED', 'Delivered'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MODERATE', max_length=20)),
                ('gestational_age_weeks', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(45)])),
                ('gestational_age_days', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)])),
                ('gravida', models.PositiveSmallIntegerField(default=1)),
                ('para', models.PositiveSmallIntegerField(default=0)),
                ('last_menstrual_period', models.DateField(blank=True, null=True)),
                ('estimated_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('enrollment_reason', models.CharField(max_length=240)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('latest_systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('latest_diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('latest_glucose_mmol_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fetal_notes', models.TextField(blank=True)),
                ('next_visit_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('enrolled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('assigned_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perinatal_registry_entries', to=settings.AUTH_USER_MODEL)),
                ('department_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perinatal_registry_entries', to='care.department')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perinatal_registry_entries', to='care.hospital')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perinatal_registry_entries', to='care.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perinatal_registry_entries', to='care.patient')),
            ],
            options={
                'ordering': ['risk_level', 'next_visit_at', 'patient__last_name'],
                'indexes': [models.Index(fields=['organization', 'status', 'risk_level'], name='care_perina_organiz_c1e074_idx'), models.Index(fields=['hospital', 'status', 'risk_level'], name='care_perina_hospita_098bcb_idx'), models.Index(fields=['patient', 'status'], name='care_perina_patient_e67af6_idx'), models.Index(fields=['estimated_due_date', 'status'], name='care_perina_estimat_d102c2_idx'), models.Index(fields=['next_visit_at', 'risk_level'], name='care_perina_next_vi_30c979_idx')],
            },
        ),
    ]
