# Generated by Django 5.2.15 on 2026-06-04 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_phase_2c_perinatal_patronage_mpi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousfeedback',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('COMPLAINT', 'Complaint'), ('SUGGESTION', 'Suggestion'), ('PRAISE', 'Praise'), ('SAFETY', 'Safety'), ('STAFF_CONDUCT', 'Staff conduct'), ('WAIT_TIME', 'Wait time'), ('CLEANLINESS', 'Cleanliness'), ('PATIENT_RIGHTS', 'Patient rights')], db_index=True, default='GENERAL', max_length=32),
        ),
        migrations.AddField(
            model_name='anonymousfeedback',
            name='language',
            field=models.CharField(default='uz-Latn', max_length=16),
        ),
        migrations.AddField(
            model_name='anonymousfeedback',
            name='phone_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='anonymousfeedback',
            name='phone_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='anonymousfeedback',
            name='requires_follow_up',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='anonymousfeedback',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='anonymousfeedback',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('TRIAGED', 'Triaged'), ('IN_REVIEW', 'In review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='anonymousfeedback',
            name='target_staff_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_feedback_received', to='care.staffprofile'),
        ),
        migrations.AddField(
            model_name='anonymousfeedback',
            name='target_type',
            field=models.CharField(choices=[('ROOM', 'Room'), ('DOCTOR', 'Doctor'), ('DEPARTMENT', 'Department'), ('HOSPITAL', 'Hospital')], db_index=True, default='ROOM', max_length=32),
        ),
        migrations.AlterField(
            model_name='anonymousfeedback',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='anonymousfeedback',
            name='room_qr_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.CreateModel(
            name='AIAssistantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('CLINICAL_COPILOT', 'Clinical co-pilot'), ('RCA_COACH', 'RCA coach'), ('DIGITAL_TWIN', 'Digital twin'), ('PERINATAL_REVIEW', 'Perinatal review'), ('PATIENT_COMMUNICATION', 'Patient communication')], db_index=True, default='CLINICAL_COPILOT', max_length=32)),
                ('safety_status', models.CharField(choices=[('DRAFT', 'Draft'), ('ADVISORY', 'Advisory'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=20)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assistant_sessions', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_assistant_sessions', to='care.hospital')),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assistant_sessions', to='care.medicalrecord')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_assistant_sessions', to='care.organization')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assistant_sessions', to='care.patient')),
                ('staff_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assistant_sessions', to='care.staffprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ASSISTANT', 'Assistant'), ('TOOL', 'Tool'), ('SAFETY', 'Safety')], db_index=True, max_length=20)),
                ('content', models.TextField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='LOW', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='care.aiassistantsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PhoneVerificationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('phone_hash', models.CharField(db_index=True, max_length=128)),
                ('phone_last4', models.CharField(blank=True, max_length=4)),
                ('purpose', models.CharField(choices=[('FEEDBACK', 'Feedback')], db_index=True, default='FEEDBACK', max_length=32)),
                ('target_type', models.CharField(choices=[('ROOM', 'Room'), ('DOCTOR', 'Doctor'), ('DEPARTMENT', 'Department'), ('HOSPITAL', 'Hospital')], db_index=True, default='ROOM', max_length=32)),
                ('room_qr_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('code_digest', models.CharField(max_length=128)),
                ('verification_token_digest', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('delivery_channel', models.CharField(default='sms', max_length=32)),
                ('delivery_status', models.CharField(default='queued', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_staff_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_verification_challenges', to='care.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='anonymousfeedback',
            name='phone_verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_submissions', to='care.phoneverificationchallenge'),
        ),
        migrations.AddIndex(
            model_name='anonymousfeedback',
            index=models.Index(fields=['target_type', 'status', 'created_at'], name='care_anonym_target__38a010_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymousfeedback',
            index=models.Index(fields=['target_staff_profile', 'created_at'], name='care_anonym_target__1ad889_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymousfeedback',
            index=models.Index(fields=['category', 'severity', 'created_at'], name='care_anonym_categor_26ae8b_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymousfeedback',
            index=models.Index(fields=['phone_hash', 'created_at'], name='care_anonym_phone_h_69908c_idx'),
        ),
        migrations.AddIndex(
            model_name='aiassistantsession',
            index=models.Index(fields=['organization', 'mode', 'updated_at'], name='care_aiassi_organiz_05a9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='aiassistantsession',
            index=models.Index(fields=['hospital', 'safety_status', 'updated_at'], name='care_aiassi_hospita_da98c2_idx'),
        ),
        migrations.AddIndex(
            model_name='aiassistantsession',
            index=models.Index(fields=['patient', 'updated_at'], name='care_aiassi_patient_bf4b35_idx'),
        ),
        migrations.AddIndex(
            model_name='aiassistantsession',
            index=models.Index(fields=['created_by', 'updated_at'], name='care_aiassi_created_a25d26_idx'),
        ),
        migrations.AddIndex(
            model_name='aiassistantmessage',
            index=models.Index(fields=['session', 'created_at'], name='care_aiassi_session_eac95b_idx'),
        ),
        migrations.AddIndex(
            model_name='aiassistantmessage',
            index=models.Index(fields=['role', 'risk_level', 'created_at'], name='care_aiassi_role_ed25e0_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverificationchallenge',
            index=models.Index(fields=['phone_hash', 'created_at'], name='care_phonev_phone_h_0dd4ef_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverificationchallenge',
            index=models.Index(fields=['target_type', 'room_qr_id'], name='care_phonev_target__251c07_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverificationchallenge',
            index=models.Index(fields=['target_staff_profile', 'created_at'], name='care_phonev_target__e91ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverificationchallenge',
            index=models.Index(fields=['expires_at', 'consumed_at'], name='care_phonev_expires_ed701d_idx'),
        ),
    ]
