# Generated by Django 5.2.15 on 2026-06-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0007_verified_feedback_ai_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousfeedback',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
