# Generated by Django 5.2.15 on 2026-06-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0008_anonymousfeedback_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousfeedback',
            name='target_doctor_label',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
    ]
